# Introduction

Surveys are one of the most common methods used to collect primary data, especially in understanding students’ experiences and perspectives. Through surveys, researchers are able to gather information directly from respondents regarding specific issues that may not be easily observed.

This project investigates the relationship between activities related to CV development and stress levels among university students. The survey focuses on students’ involvement in activities such as organizations, competitions, seminars, internships, and other experiences intended to support career preparation and improve their CVs.

However, survey-based research is also sensitive to several limitations, such as respondent bias, differences in individual interpretations of questions, and limited sample size. Therefore, this project also considers the reliability of the collected data and several factors that may influence the survey results.

# Overview
The dataset used in this study consists of responses collected from 35 university students through an online questionnaire. The survey focuses on students’ activities related to CV development, such as participation in organizations, competitions, seminars, internships, and other self-development activities, as well as the stress experienced by students during these activities.

The dataset contains respondent demographic information, including age, gender, study program, and semester level. In addition, the questionnaire includes several Likert-scale questions related to CV development activities and student stress levels.

Since the survey was conducted using close-ended questions and Likert scales, respondents selected answers based on predefined options. While this approach simplifies data collection and analysis, it also limits the depth of respondents’ explanations and experiences regarding the topic.

In [ ]:
# library for data handling
import numpy as np # mengolah data numeric
import pandas as pd # mengelola dataframe --> cleaning, filtering, sorting, dsb

# library for data visualisation
import matplotlib.pyplot as plt # visualisasi seerhana / basic
import seaborn as sns # visualisasi dengan warna dan setting yang lebih atraktif

sns.set_style("whitegrid")

In [ ]:
import pandas as pd

raw_df = pd.read_excel("data kuiseoner.csv.xlsx")

raw_df

,Timestamp,Nama (Opsional),Program Studi,Semester,Jenis Kelamin,Apakah kamu sudah mulai membuat CV?,"Apakah kamu pernah mengikuti kegiatan seperti magang, organisasi, atau lomba?",Saya merasa tertekan karena harus memiliki CV yang lengkap dan menarik sebelum lulus.,Saya khawatir pengalaman organisasi atau kepanitiaan saya tidak cukup untuk dimasukkan ke CV.,"Saya merasa teman-teman memiliki pencapaian yang lebih banyak dibanding saya (misalnya magang, proyek, sertifikat).",...,Saya menghabiskan waktu yang sangat lama hanya untuk memikirkan atau memperbaiki tampilan CV.,Saya sering merasa cemas memikirkan masa depan karier saya.,Saya merasa cemas ketika tidak mengikuti kegiatan yang dapat menambah pengalaman saya.,"Saya merasa kewalahan dalam menjalani berbagai kegiatan seperti organisasi, lomba, atau pelatihan.",Saya merasa kewalahan dengan banyaknya hal yang harus disiapkan selama kuliah.,Saya merasa terbebani dengan banyaknya kegiatan yang saya jalani di luar perkuliahan.,Saya merasa lelah secara fisik atau pusing ketika memikirkan target pencapaian yang belum tercapai.,Saya merasa stres ketika melihat teman yang sudah mendapat pengalaman kerja atau magang.,Kegiatan tambahan yang saya jalani mempengaruhi kondisi mental saya.,Saya merasa takut tidak siap saat nanti terjun ke dunia kerja.
0,2026-06-05 10:07:40,Clara Maisie Wanghili,S1 â€“ Sains Data,semester 2,Perempuan,"Sudah, tapi belum selesai",Ya,4,4,4,...,3,5,5,3,4,3,4,4,4,5
1,2026-06-05 10:12:56,Muhammad Nabil Khairil Anam,S1 â€“ Sains Data,semester 2,Laki-laki,"Sudah, tapi belum selesai",Tidak,3,3,4,...,3,4,4,3,3,4,4,3,2,1
2,2026-06-05 10:37:42,Safina Zahra,S1 â€“ Sains Data,semester 2,Perempuan,"Sudah, tapi belum selesai",Tidak,3,4,4,...,3,5,5,4,4,3,2,1,1,1
3,2026-06-05 11:02:21,NaN,S1 â€“ Sains Data,semester 2,Perempuan,"Sudah, tapi belum selesai",Ya,5,5,5,...,3,5,4,3,3,2,4,3,1,3
4,2026-06-05 11:13:42,najwa,S1 â€“ Teknik Perminyakan,semester 2,Perempuan,"Sudah, tapi belum selesai",Tidak,3,4,4,...,3,5,4,3,3,3,4,4,3,4
5,2026-06-05 11:34:22,Ulin Nikmah,S1 â€“ Sains Data,semester 2,Perempuan,"Sudah, tapi belum selesai",Ya,2,4,3,...,2,3,4,3,3,2,3,2,4,4
6,2026-06-05 11:36:20,Chelsea Tesalonika,S1 â€“ Sains Data,semester 2,Perempuan,Tidak,Ya,5,4,3,...,5,5,5,4,5,5,5,5,5,5
7,2026-06-05 12:22:00,Annisa Mutya Amanda,S1 â€“ Teknik Metalurgi,semester 2,Perempuan,"Sudah, tapi belum selesai",Ya,3,5,5,...,2,5,5,5,3,2,3,5,4,5
8,2026-06-05 13:11:09,Wulan Gustika Antasya Tumanggor,S1 â€“ Sains Data,semester 2,Perempuan,Tidak,Tidak,3,3,3,...,3,3,3,3,3,3,3,3,3,3
9,2026-06-05 21:47:18,Paskalis Farelnata,S1 â€“ Sains Data,semester 2,Laki-laki,Tidak,Ya,3,3,3,...,3,3,4,3,3,3,3,3,3,3
10,2026-09-05 07:52:02,aryaf,S1 â€“ Sains Data,semester 2,Laki-laki,"Sudah, tapi belum selesai",Ya,2,2,2,...,1,4,4,3,3,3,3,3,3,3
11,2026-09-05 18:06:30,Nurul Iffah,S1 â€“ Sains Data,semester 2,Perempuan,"Sudah, tapi belum selesai",Ya,4,4,4,...,4,5,5,5,5,2,4,4,4,5
12,2026-09-05 18:11:24,Arm,S1 â€“ Sains Data,semester 2,Laki-laki,Tidak,Ya,3,2,3,...,1,4,3,3,3,3,4,3,3,3
13,2026-09-05 18:13:00,M. Yustian,S1 â€“ Sains Data,semester 2,Laki-laki,"Sudah, tapi belum selesai",Ya,3,1,1,...,2,3,3,2,3,3,3,1,3,3
14,2026-09-05 18:18:59,NaN,S1 â€“ Informatika,semester 2,Laki-laki,Tidak,Ya,4,4,4,...,4,5,4,4,4,4,3,3,4,5
15,2026-09-05 18:33:15,Yosef Teofani Tamba,S1 â€“ Sains Data,semester 2,Laki-laki,Tidak,Ya,4,5,5,...,3,5,5,2,4,4,5,4,4,5
16,2026-09-05 18:56:50,Dhefio Alim Muzakki,S1 â€“ Sains Data,semester 2,Laki-laki,Ya,Ya,3,3,3,...,3,3,2,4,3,2,2,2,3,3
17,2026-10-05 08:47:33,FRENKHY TONGA RETANG,S1 â€“ Sains Data,semester 2,Laki-laki,Ya,Ya,1,3,3,...,2,1,1,3,2,2,2,1,2,2
18,2026-10-05 15:05:30,Nabila Zahwa Azzahra,S1 â€“ Perencanaan Wilayah dan Kota,semester 2,Perempuan,Ya,Ya,4,4,4,...,4,5,4,3,4,3,5,5,5,5
19,2026-10-05 16:06:41,Hirose kawarin sirait,S1 â€“ Sains Data,semester 2,Perempuan,Tidak,Ya,3,4,3,...,3,5,3,3,4,3,4,3,3,3
20,2026-11-05 08:29:42,nisa,S1 â€“ Sains Data,semester 2,Perempuan,"Sudah, tapi belum selesai",Ya,3,5,4,...,4,4,4,4,4,3,4,4,4,4
21,2026-11-05 08:53:21,Jihan Ramadhani Deandri,S1 â€“ Sains Data,semester 2,Perempuan,Ya,Tidak,3,3,3,...,3,3,3,3,3,3,3,3,3,3
22,2026-11-05 10:00:00,NaN,S1 â€“ Informatika,semester 2,Laki-laki,"Sudah, tapi belum selesai",Ya,4,4,4,...,4,4,4,4,4,3,4,4,3,5
23,13/05/2026 17:13:09,idhor ignasius,S1 â€“ Sains Data,semester 2,Laki-laki,Ya,Ya,3,3,3,...,3,4,4,4,4,3,3,2,3,4
24,14/05/2026 8:42:50,Raihania syah putri,S1 â€“ Sains Data,semester 2,Perempuan,Ya,Ya,4,5,5,...,3,5,5,5,5,5,4,4,3,4
25,14/05/2026 8:50:12,Anindya Kristianingputri,S1 â€“ Sains Data,semester 2,Perempuan,"Sudah, tapi belum selesai",Ya,3,4,5,...,5,5,5,3,2,2,5,5,3,4
26,14/05/2026 9:16:08,Lulu Najla Salsabila,S1 â€“ Sains Data,semester 2,Perempuan,Ya,Tidak,4,5,5,...,4,5,5,3,4,2,4,2,3,5
27,14/05/2026 9:33:56,vanes,S1 â€“ Sains Data,semester 2,Perempuan,Ya,Ya,4,5,5,...,3,4,3,3,3,3,3,3,3,2
28,14/05/2026 11:18:20,Naila,S1 â€“ Sains Data,semester 2,Perempuan,Tidak,Ya,3,5,4,...,5,5,4,3,3,3,3,4,3,5
29,14/05/2026 19:34:27,Fifi kelas A,S1 â€“ Sains Data,semester 2,Perempuan,Ya,Ya,4,5,3,...,5,5,4,4,4,2,4,3,2,4
30,14/05/2026 19:53:15,NaN,S1 â€“ Teknik Perminyakan,semester 2,Laki-laki,"Sudah, tapi belum selesai",Ya,3,4,3,...,4,3,3,4,4,1,2,2,2,3
31,14/05/2026 19:55:27,NaN,S1 â€“ Perencanaan Wilayah dan Kota,semester 2,NaN,Ya,Ya,1,2,2,...,2,3,3,3,2,2,2,2,2,2
32,14/05/2026 20:12:53,NaN,S1 â€“ Teknik Perminyakan,semester 2,Perempuan,"Sudah, tapi belum selesai",Ya,5,5,5,...,5,5,4,3,4,3,4,5,3,5
33,14/05/2026 20:15:25,NaN,S1 â€“ Teknik Metalurgi,semester 2,Perempuan,Tidak,Tidak,3,3,3,...,3,3,3,3,3,3,3,3,3,3
34,14/05/2026 20:52:38,Lia,S1 â€“ Teknik Pertambangan,semester 2,Perempuan,Tidak,Ya,3,4,5,...,3,5,3,5,5,3,5,3,5,5

In [ ]:
# overview of the data
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 23 columns):
 #   Column                                                                                                               Non-Null Count  Dtype
---  ------                                                                                                               --------------  -----
 0   Timestamp                                                                                                            35 non-null     object
 1   Nama (Opsional)                                                                                                      28 non-null     object
 2   Program Studi                                                                                                        35 non-null     object
 3   Semester                                                                                                             35 non-null     object
 4   Jenis Kelamin                                                                                                        34 non-null     object
 5   Apakah kamu sudah mulai membuat CV?                                                                                  35 non-null     object
 6   Apakah kamu pernah mengikuti kegiatan seperti magang, organisasi, atau lomba?                                        35 non-null     object
 7   Saya merasa tertekan karena harus memiliki CV yang lengkap dan menarik sebelum lulus.                                35 non-null     int64
 8   Saya khawatir pengalaman organisasi atau kepanitiaan saya tidak cukup untuk dimasukkan ke CV.                        35 non-null     int64
 9   Saya merasa teman-teman memiliki pencapaian yang lebih banyak dibanding saya (misalnya magang, proyek, sertifikat).  35 non-null     int64
 10  Saya merasa ada tuntutan eksternal untuk mengambil banyak kegiatan demi mempercantik CV.                             35 non-null     int64
 11  Saya sering membandingkan CV saya dengan CV orang lain (dari media sosial, LinkedIn, dll.).                          35 non-null     int64
 12  Tekanan untuk membangun CV terasa meningkat menjelang semester akhir atau masa rekrutmen kerja.                      35 non-null     int64
 13  Saya menghabiskan waktu yang sangat lama hanya untuk memikirkan atau memperbaiki tampilan CV.                        35 non-null     int64
 14  Saya sering merasa cemas memikirkan masa depan karier saya.                                                          35 non-null     int64
 15  Saya merasa cemas ketika tidak mengikuti kegiatan yang dapat menambah pengalaman saya.                               35 non-null     int64
 16  Saya merasa kewalahan dalam menjalani berbagai kegiatan seperti organisasi, lomba, atau pelatihan.                   35 non-null     int64
 17  Saya merasa kewalahan dengan banyaknya hal yang harus disiapkan selama kuliah.                                       35 non-null     int64
 18  Saya merasa terbebani dengan banyaknya kegiatan yang saya jalani di luar perkuliahan.                                35 non-null     int64
 19  Saya merasa lelah secara fisik atau pusing ketika memikirkan target pencapaian yang belum tercapai.                  35 non-null     int64
 20  Saya merasa stres ketika melihat teman yang sudah mendapat pengalaman kerja atau magang.                             35 non-null     int64
 21  Kegiatan tambahan yang saya jalani mempengaruhi kondisi mental saya.                                                 35 non-null     int64
 22  Saya merasa takut tidak siap saat nanti terjun ke dunia kerja.                                                       35 non-null     int64
dtypes: int64(16), object(7)
memory usage: 6.4+ KB

There are also several incomplete responses in the dataset, as some participants chose not to answer certain questions. In particular, the name field was intentionally made optional to maintain respondent comfort and privacy. As a result, some entries contain missing values in that section.

It should also be noted that this study focuses on analyzing the responses collected from the questionnaire and understanding their implications regarding students’ CV development activities and stress levels. Therefore, the project mainly evaluates the survey responses and the overall quality of the dataset rather than examining potential bias in the wording of the survey questions.

# Examining Individual Variables
In this study, the questionnaire was designed to examine two main variables: activities related to CV development and students’ stress levels. Since the data were collected through an online survey, each variable needs to be examined carefully to understand the quality and consistency of the responses.

The analysis of individual variables is important to identify patterns in students’ responses, evaluate the completeness of the data, and determine whether the questionnaire items are able to represent the intended variables effectively. Through this process, potential limitations such as incomplete responses or differences in respondent interpretation can also be identified.

In [ ]:
raw_df.head(20)

,Timestamp,Nama (Opsional),Program Studi,Semester,Jenis Kelamin,Apakah kamu sudah mulai membuat CV?,"Apakah kamu pernah mengikuti kegiatan seperti magang, organisasi, atau lomba?",Saya merasa tertekan karena harus memiliki CV yang lengkap dan menarik sebelum lulus.,Saya khawatir pengalaman organisasi atau kepanitiaan saya tidak cukup untuk dimasukkan ke CV.,"Saya merasa teman-teman memiliki pencapaian yang lebih banyak dibanding saya (misalnya magang, proyek, sertifikat).",...,Saya menghabiskan waktu yang sangat lama hanya untuk memikirkan atau memperbaiki tampilan CV.,Saya sering merasa cemas memikirkan masa depan karier saya.,Saya merasa cemas ketika tidak mengikuti kegiatan yang dapat menambah pengalaman saya.,"Saya merasa kewalahan dalam menjalani berbagai kegiatan seperti organisasi, lomba, atau pelatihan.",Saya merasa kewalahan dengan banyaknya hal yang harus disiapkan selama kuliah.,Saya merasa terbebani dengan banyaknya kegiatan yang saya jalani di luar perkuliahan.,Saya merasa lelah secara fisik atau pusing ketika memikirkan target pencapaian yang belum tercapai.,Saya merasa stres ketika melihat teman yang sudah mendapat pengalaman kerja atau magang.,Kegiatan tambahan yang saya jalani mempengaruhi kondisi mental saya.,Saya merasa takut tidak siap saat nanti terjun ke dunia kerja.
0,2026-06-05 10:07:40,Clara Maisie Wanghili,S1 â€“ Sains Data,semester 2,Perempuan,"Sudah, tapi belum selesai",Ya,4,4,4,...,3,5,5,3,4,3,4,4,4,5
1,2026-06-05 10:12:56,Muhammad Nabil Khairil Anam,S1 â€“ Sains Data,semester 2,Laki-laki,"Sudah, tapi belum selesai",Tidak,3,3,4,...,3,4,4,3,3,4,4,3,2,1
2,2026-06-05 10:37:42,Safina Zahra,S1 â€“ Sains Data,semester 2,Perempuan,"Sudah, tapi belum selesai",Tidak,3,4,4,...,3,5,5,4,4,3,2,1,1,1
3,2026-06-05 11:02:21,NaN,S1 â€“ Sains Data,semester 2,Perempuan,"Sudah, tapi belum selesai",Ya,5,5,5,...,3,5,4,3,3,2,4,3,1,3
4,2026-06-05 11:13:42,najwa,S1 â€“ Teknik Perminyakan,semester 2,Perempuan,"Sudah, tapi belum selesai",Tidak,3,4,4,...,3,5,4,3,3,3,4,4,3,4
5,2026-06-05 11:34:22,Ulin Nikmah,S1 â€“ Sains Data,semester 2,Perempuan,"Sudah, tapi belum selesai",Ya,2,4,3,...,2,3,4,3,3,2,3,2,4,4
6,2026-06-05 11:36:20,Chelsea Tesalonika,S1 â€“ Sains Data,semester 2,Perempuan,Tidak,Ya,5,4,3,...,5,5,5,4,5,5,5,5,5,5
7,2026-06-05 12:22:00,Annisa Mutya Amanda,S1 â€“ Teknik Metalurgi,semester 2,Perempuan,"Sudah, tapi belum selesai",Ya,3,5,5,...,2,5,5,5,3,2,3,5,4,5
8,2026-06-05 13:11:09,Wulan Gustika Antasya Tumanggor,S1 â€“ Sains Data,semester 2,Perempuan,Tidak,Tidak,3,3,3,...,3,3,3,3,3,3,3,3,3,3
9,2026-06-05 21:47:18,Paskalis Farelnata,S1 â€“ Sains Data,semester 2,Laki-laki,Tidak,Ya,3,3,3,...,3,3,4,3,3,3,3,3,3,3
10,2026-09-05 07:52:02,aryaf,S1 â€“ Sains Data,semester 2,Laki-laki,"Sudah, tapi belum selesai",Ya,2,2,2,...,1,4,4,3,3,3,3,3,3,3
11,2026-09-05 18:06:30,Nurul Iffah,S1 â€“ Sains Data,semester 2,Perempuan,"Sudah, tapi belum selesai",Ya,4,4,4,...,4,5,5,5,5,2,4,4,4,5
12,2026-09-05 18:11:24,Arm,S1 â€“ Sains Data,semester 2,Laki-laki,Tidak,Ya,3,2,3,...,1,4,3,3,3,3,4,3,3,3
13,2026-09-05 18:13:00,M. Yustian,S1 â€“ Sains Data,semester 2,Laki-laki,"Sudah, tapi belum selesai",Ya,3,1,1,...,2,3,3,2,3,3,3,1,3,3
14,2026-09-05 18:18:59,NaN,S1 â€“ Informatika,semester 2,Laki-laki,Tidak,Ya,4,4,4,...,4,5,4,4,4,4,3,3,4,5
15,2026-09-05 18:33:15,Yosef Teofani Tamba,S1 â€“ Sains Data,semester 2,Laki-laki,Tidak,Ya,4,5,5,...,3,5,5,2,4,4,5,4,4,5
16,2026-09-05 18:56:50,Dhefio Alim Muzakki,S1 â€“ Sains Data,semester 2,Laki-laki,Ya,Ya,3,3,3,...,3,3,2,4,3,2,2,2,3,3
17,2026-10-05 08:47:33,FRENKHY TONGA RETANG,S1 â€“ Sains Data,semester 2,Laki-laki,Ya,Ya,1,3,3,...,2,1,1,3,2,2,2,1,2,2
18,2026-10-05 15:05:30,Nabila Zahwa Azzahra,S1 â€“ Perencanaan Wilayah dan Kota,semester 2,Perempuan,Ya,Ya,4,4,4,...,4,5,4,3,4,3,5,5,5,5
19,2026-10-05 16:06:41,Hirose kawarin sirait,S1 â€“ Sains Data,semester 2,Perempuan,Tidak,Ya,3,4,3,...,3,5,3,3,4,3,4,3,3,3

In [ ]:
# check missing value

raw_df.isnull().sum()

Timestamp                                                                                                              0
Nama (Opsional)                                                                                                        7
Program Studi                                                                                                          0
Semester                                                                                                               0
Jenis Kelamin                                                                                                          1
Apakah kamu sudah mulai membuat CV?                                                                                    0
Apakah kamu pernah mengikuti kegiatan seperti magang, organisasi, atau lomba?                                          0
Saya merasa tertekan karena harus memiliki CV yang lengkap dan menarik sebelum lulus.                                  0
Saya khawatir pengalaman organisasi atau kepanitiaan saya tidak cukup untuk dimasukkan ke CV.                          0
Saya merasa teman-teman memiliki pencapaian yang lebih banyak dibanding saya (misalnya magang, proyek, sertifikat).    0
Saya merasa ada tuntutan eksternal untuk mengambil banyak kegiatan demi mempercantik CV.                               0
Saya sering membandingkan CV saya dengan CV orang lain (dari media sosial, LinkedIn, dll.).                            0
Tekanan untuk membangun CV terasa meningkat menjelang semester akhir atau masa rekrutmen kerja.                        0
Saya menghabiskan waktu yang sangat lama hanya untuk memikirkan atau memperbaiki tampilan CV.                          0
Saya sering merasa cemas memikirkan masa depan karier saya.                                                            0
Saya merasa cemas ketika tidak mengikuti kegiatan yang dapat menambah pengalaman saya.                                 0
Saya merasa kewalahan dalam menjalani berbagai kegiatan seperti organisasi, lomba, atau pelatihan.                     0
Saya merasa kewalahan dengan banyaknya hal yang harus disiapkan selama kuliah.                                         0
Saya merasa terbebani dengan banyaknya kegiatan yang saya jalani di luar perkuliahan.                                  0
Saya merasa lelah secara fisik atau pusing ketika memikirkan target pencapaian yang belum tercapai.                    0
Saya merasa stres ketika melihat teman yang sudah mendapat pengalaman kerja atau magang.                               0
Kegiatan tambahan yang saya jalani mempengaruhi kondisi mental saya.                                                   0
Saya merasa takut tidak siap saat nanti terjun ke dunia kerja.                                                         0
CV Score                                                                                                               0
dtype: int64



Most variables in the dataset do not contain missing values, indicating that respondents completed the questionnaire properly.

However, there are:

- 7 missing values in the “Nama (Opsional)” column because the name field was optional.
- 1 missing value in the “Jenis Kelamin” column.

Overall, the dataset is sufficiently complete and suitable for further analysis.

In [ ]:
# create cleaned dataframe
df = raw_df.copy()

In [ ]:
raw_df.columns

Index(['Timestamp', 'Nama (Opsional)', 'Program Studi', 'Semester',
       'Jenis Kelamin', 'Apakah kamu sudah mulai membuat CV?',
       'Apakah kamu pernah mengikuti kegiatan seperti magang, organisasi, atau lomba? ',
       'Saya merasa tertekan karena harus memiliki CV yang lengkap dan menarik sebelum lulus. ',
       'Saya khawatir pengalaman organisasi atau kepanitiaan saya tidak cukup untuk dimasukkan ke CV.',
       'Saya merasa teman-teman memiliki pencapaian yang lebih banyak dibanding saya (misalnya magang, proyek, sertifikat).',
       'Saya merasa ada tuntutan eksternal untuk mengambil banyak kegiatan demi mempercantik CV.',
       'Saya sering membandingkan CV saya dengan CV orang lain (dari media sosial, LinkedIn, dll.).',
       'Tekanan untuk membangun CV terasa meningkat menjelang semester akhir atau masa rekrutmen kerja.',
       'Saya menghabiskan waktu yang sangat lama hanya untuk memikirkan atau memperbaiki tampilan CV.',
       'Saya sering merasa cemas memikirkan masa depan karier saya.',
       'Saya merasa cemas ketika tidak mengikuti kegiatan yang dapat menambah pengalaman saya.',
       'Saya merasa kewalahan dalam menjalani berbagai kegiatan seperti organisasi, lomba, atau pelatihan.',
       'Saya merasa kewalahan dengan banyaknya hal yang harus disiapkan selama kuliah.',
       'Saya merasa terbebani dengan banyaknya kegiatan yang saya jalani di luar perkuliahan.',
       'Saya merasa lelah secara fisik atau pusing ketika memikirkan target pencapaian yang belum tercapai.',
       'Saya merasa stres ketika melihat teman yang sudah mendapat pengalaman kerja atau magang.',
       'Kegiatan tambahan yang saya jalani mempengaruhi kondisi mental saya.',
       'Saya merasa takut tidak siap saat nanti terjun ke dunia kerja.',
       'CV Score'],
      dtype='object')

In [ ]:
x_columns = [
    "Saya merasa tertekan karena harus memiliki CV yang lengkap dan menarik sebelum lulus. ",
    "Saya khawatir pengalaman organisasi atau kepanitiaan saya tidak cukup untuk dimasukkan ke CV.",
    "Saya khawatir pengalaman organisasi atau kepanitiaan saya tidak cukup untuk dimasukkan ke CV.",
    "Saya merasa teman-teman memiliki pencapaian yang lebih banyak dibanding saya (misalnya magang, proyek, sertifikat).",
    "Saya merasa ada tuntutan eksternal untuk mengambil banyak kegiatan demi mempercantik CV.",
    "Saya sering membandingkan CV saya dengan CV orang lain (dari media sosial, LinkedIn, dll.).",
    "Tekanan untuk membangun CV terasa meningkat menjelang semester akhir atau masa rekrutmen kerja.",
    "Saya menghabiskan waktu yang sangat lama hanya untuk memikirkan atau memperbaiki tampilan CV."
]


raw_df["CV Score"] = raw_df[x_columns].mean(axis=1)

In [ ]:
y_columns = [
    "Saya sering merasa cemas memikirkan masa depan karier saya.",
    "Saya merasa cemas ketika tidak mengikuti kegiatan yang dapat menambah pengalaman saya.",
    "Saya merasa kewalahan dalam menjalani berbagai kegiatan seperti organisasi, lomba, atau pelatihan.",
    "Saya merasa kewalahan dengan banyaknya hal yang harus disiapkan selama kuliah.",
    "Saya merasa terbebani dengan banyaknya kegiatan yang saya jalani di luar perkuliahan.",
    "Saya merasa lelah secara fisik atau pusing ketika memikirkan target pencapaian yang belum tercapai.",
    "Saya merasa stres ketika melihat teman yang sudah mendapat pengalaman kerja atau magang.",
    "Kegiatan tambahan yang saya jalani mempengaruhi kondisi mental saya.",
    "Saya merasa takut tidak siap saat nanti terjun ke dunia kerja."
]

raw_df["Stress Score"] = raw_df[y_columns].mean(axis=1)

In [ ]:
correlation = raw_df["CV Score"].corr(raw_df["Stress Score"])

print("Correlation:", correlation)

Correlation: 0.6890702273978914

A correlation value of 0.68 indicates a strong positive relationship between CV development activities and student stress levels. This suggests that the greater the student's involvement in CV development activities, the higher their stress levels tend to be.

In [ ]:
# import library
import plotly.express as px

# create interactive scatter plot
fig = px.scatter(
    raw_df,
    x="CV Score",
    y="Stress Score",
    hover_data=["Semester", "Jenis Kelamin"],
    title="Relationship between CV Development Activities and Student Stress Levels",
    labels={
        "CV Score": "CV Development Score",
        "Stress Score": "Stress Level Score"
    }
)

# update layout
fig.update_layout(
    width=1000,
    height=600,
    title_font_size=20
)

# show graph
fig.show()

In [ ]:
import plotly.express as px
import pandas as pd

# kategorisasi score
raw_df["CV Category"] = pd.cut(
    raw_df["CV Score"],
    bins=[1, 2, 3, 4, 5],
    labels=["Very Low", "Low", "High", "Very High"]
)

raw_df["Stress Category"] = pd.cut(
    raw_df["Stress Score"],
    bins=[1, 2, 3, 4, 5],
    labels=["Very Low", "Low", "High", "Very High"]
)

# membuat crosstab
cv_stress_ct = pd.crosstab(
    raw_df["CV Category"],
    raw_df["Stress Category"]
)

# ubah ke format dataframe
heatmap_data = cv_stress_ct.reset_index().melt(
    id_vars='CV Category',
    var_name='Stress Category',
    value_name='Count'
)

# membuat interactive heatmap
fig = px.density_heatmap(
    heatmap_data,
    x="Stress Category",
    y="CV Category",
    z="Count",
    text_auto=True,
    color_continuous_scale="Purples",
    title="Relationship Between CV Development Activities and Stress Levels"
)

# update layout
fig.update_layout(
    width=900,
    height=600
)

# tampilkan grafik
fig.show()